// Every public name of the TrueSeal API (trueseal-sync ADR-0028, as amended by ADR-0029, ADR-0032 and ADR-0034),
// with its spelling in Swift, Kotlin and TypeScript. Spellings follow the ADR-0028 sketch (`sketch: true`) where the
// ADRs leave them open. Today's SDKs predate ADR-0028 (`gap`); a name no ADR or the sketch settles carries a `todo`.
import type { ApiReference } from './api.ts';

const adr = 'trueseal-sync ADR-0028';
const missingToday = 'missing from all three SDKs today (SYNC-15)';
const subscribeGap = 'today Swift uses `AsyncStream`s, Kotlin a cold `Flow` and TS an `EventEmitter`; none returns a `Subscription` (SYNC-15)';
const typeNameTodo = 'TODO: the sketch names the Kotlin event and delivery-issue types only; no ADR names the Swift and TS ones.';

export const apiReference = {
  entries: [
    {
      section: 'open', name: 'import', kind: 'module',
      platforms: { swift: 'import TrueSealSync', kotlin: 'import dev.trueseal.sync.*', typescript: 'import { TrueSeal, RelayAddress, TrueSealError } from "@trueseal/sync"' },
      meaning: 'Each SDK is one package with one public module.',
      source: { adr: [adr, 'trueseal-sync ADR-0030'], sketch: true },
      gap: 'today the Swift module is `TruesealSync`, Kotlin ships from JitPack coordinates, and the TS package is `trueseal-sync-ts`',
    },
    {
      section: 'open', name: 'TrueSeal', kind: 'type', shared: 'TrueSeal',
      platforms: { swift: '@Observable class TrueSeal', kotlin: 'class TrueSeal : Closeable', typescript: 'class TrueSeal' },
      meaning: 'One device in one namespace. The object outlives group membership. After a removal, `leave()` or `destroyGroup()`, the library wipes the namespace, makes a fresh identity and reports `statusChanged(notJoined, reason)`, and the same object can pair again.',
      action: 'Open one object per namespace when the app starts and keep it. Never rebuild it after leaving a group.',
      source: { adr: [adr], sketch: true },
      gap: 'today the type is `TruesealSyncClient` in all three SDKs, and `destroyGroup` leaves it unusable',
    },
    {
      section: 'open', name: 'TrueSeal.open', kind: 'method',
      shared: 'static async open(relay: RelayAddress | string, storage: Storage, namespace: string = "default", maxPayloadBytes?: int) -> TrueSeal',
      platforms: {
        swift: 'static func open(relay: RelayAddress, storage: Storage, namespace: String = "default", maxPayloadBytes: Int? = nil) async throws -> TrueSeal',
        kotlin: 'suspend fun open(relay: RelayAddress, storage: Storage, namespace: String = "default", maxPayloadBytes: Int? = null): TrueSeal',
        typescript: 'static open(options: { relay: RelayAddress | string; storageDir?: string; namespace?: string; maxPayloadBytes?: number }): Promise<TrueSeal>',
      },
      meaning: 'Opens the device stored in `storage` under `namespace`. It returns before the relay connection is up and connects in the background, and `send()` works at once. `maxPayloadBytes` may lower the Protocol Size Limit; a higher value is clamped to it.',
      throws: ['invalidRelayAddress', 'invalidNamespace', 'storage', 'storeTooNew'],
      facts: ['protocolSizeLimit'],
      source: { adr: [adr, 'trueseal-sync ADR-0025', 'trueseal-sync ADR-0032'], sketch: true },
      gap: 'today Swift and TS construct `TruesealSyncClient` directly, and the Kotlin constructor takes a `Context`',
      todo: 'TODO: the sketch shows the Swift and Kotlin `open` taking a `RelayAddress` only; no ADR says how they take the string form.',
    },
    {
      section: 'open', name: 'close', kind: 'method', shared: 'async close()',
      platforms: { swift: 'func close() async', kotlin: 'fun close()', typescript: 'close(): Promise<void>' },
      meaning: 'Stops the relay connection and every handler, and keeps Session State. After `close()`, every call fails with `closed`.',
      source: { adr: [adr], sketch: true },
      gap: 'Swift has no `close()` today, and TS has `dispose()`',
    },
    {
      section: 'open', name: 'RelayAddress', kind: 'type',
      shared: 'RelayAddress(host: string, publicKey: string, receivePort?: int, pushPort?: int)',
      platforms: {
        swift: 'RelayAddress(host: String, publicKey: String, receivePort: Int, pushPort: Int)',
        kotlin: 'RelayAddress(host: String, publicKey: String, receivePort: Int, pushPort: Int)',
        typescript: 'new RelayAddress({ host, publicKey, receivePort, pushPort })',
      },
      meaning: 'The typed form of a Relay Address. `TrueSeal.open` takes it or the string the relay CLI prints. The port is never dropped.',
      facts: ['relayAddressFormat', 'defaultReceivePort', 'defaultPushPort'],
      source: { adr: [adr], sketch: true },
      gap: 'today the SDKs take a host and a key, and Swift drops the port; `ffi.rs` `TruesealFfiSession::create` takes a host and no port',
    },
    {
      section: 'open', name: 'RelayAddress.parse', kind: 'method', shared: 'RelayAddress.parse(address: string) -> RelayAddress',
      platforms: { swift: 'RelayAddress(_ address: String) throws', kotlin: 'RelayAddress.parse(address: String): RelayAddress', typescript: 'RelayAddress.parse(address: string): RelayAddress' },
      meaning: 'Reads a Relay Address string into the typed form.',
      action: 'Use it to check a configured address before calling `TrueSeal.open`.',
      source: { adr: [adr], sketch: true },
      gap: missingToday,
      todo: 'TODO: no ADR says what `parse` throws on a bad string.',
    },
    {
      section: 'open', name: 'Storage', kind: 'type', shared: 'Storage',
      platforms: {
        swift: 'Storage.applicationSupport | Storage.directory(URL)',
        kotlin: 'Storage.android(context) | Storage.directory(File)',
        typescript: 'storageDir?: string (an option of TrueSeal.open)',
      },
      meaning: 'Where Session State lives. Kotlin always takes an explicit location, and `Storage.android(context)` builds it from an Android context.',
      source: { adr: [adr], sketch: true },
      gap: missingToday,
      todo: 'TODO: no ADR names the TS default directory.',
    },
    {
      section: 'state', name: 'status', kind: 'property', shared: 'status: GroupStatus',
      platforms: { swift: 'var status: GroupStatus', kotlin: 'val status: StateFlow<GroupStatus>', typescript: 'readonly status: GroupStatus' },
      meaning: 'Where this device is in a Sync Group. Swift observes it through `@Observable`, Kotlin through `StateFlow`, and TS through the `statusChanged` event.',
      source: { adr: [adr], sketch: true },
      gap: missingToday,
    },
    {
      section: 'state', name: 'me', kind: 'property', shared: 'me: Member',
      platforms: { swift: 'var me: Member', kotlin: 'val me: Member', typescript: 'readonly me: Member' },
      meaning: 'This device. Its `id` changes when the library makes a fresh identity.',
      source: { adr: [adr], sketch: true },
      gap: 'today each SDK has `localNodeId` and `localDeviceName` instead of `me`',
    },
    {
      section: 'state', name: 'members', kind: 'property', shared: 'members: Member[]',
      platforms: { swift: 'var members: [Member]', kotlin: 'val members: StateFlow<List<Member>>', typescript: 'readonly members: Member[]' },
      meaning: 'Every other member of the Sync Group, as a whole list and never a delta. It can briefly show a member leave and rejoin while a concurrent change is re-applied.',
      action: 'Render the whole list each time it changes.',
      source: { adr: [adr, 'trueseal-sync ADR-0027'], sketch: true },
      gap: 'today `members` reads a snapshot on each access, of `SyncMember` in Swift and Kotlin, and changes arrive on a separate stream or event',
    },
    {
      section: 'state', name: 'connection', kind: 'property', shared: 'connection: Connection',
      platforms: { swift: 'var connection: Connection', kotlin: 'val connection: StateFlow<Connection>', typescript: 'readonly connection: Connection' },
      meaning: 'The relay connection. TS reports changes through the `connectionChanged` event.',
      source: { adr: [adr], sketch: true },
      gap: 'today each SDK has its own connection stream or event',
    },
    {
      section: 'state', name: 'GroupStatus', kind: 'type', shared: 'GroupStatus', valueSet: 'status',
      platforms: { swift: 'enum GroupStatus', kotlin: 'GroupStatus', typescript: 'type GroupStatus' },
      meaning: 'The device\'s place in a Sync Group. `destroying` lasts until the relay has accepted a Revoke for every member, with no timeout.',
      source: { adr: [adr, 'trueseal-sync ADR-0029'], sketch: true },
      gap: missingToday,
    },
    {
      section: 'state', name: 'Connection', kind: 'type', shared: 'Connection', valueSet: 'connection', tsValues: 'state',
      platforms: { swift: 'enum Connection', kotlin: 'Connection', typescript: 'type Connection' },
      meaning: 'The relay connection state. `relayVersionUnsupported` carries the Transport Versions the relay accepts; versions are never negotiated.',
      source: { adr: [adr, 'trueseal-sync ADR-0022'], sketch: true },
      gap: 'today Swift and Kotlin stream a `ConnectionState`, and TS emits `connectionChanged` with a boolean',
    },
    {
      section: 'state', name: 'Member', kind: 'type', shared: 'Member{id, name}',
      platforms: { swift: 'Member(id:name:)', kotlin: 'Member(id, name)', typescript: 'interface Member { id; name }' },
      meaning: 'A device in the Sync Group. `name` is a label the device chose, never authentication.',
      source: { adr: [adr, 'trueseal-sync ADR-0023'], sketch: true },
      gap: 'today Swift and Kotlin call the type `SyncMember`',
    },
    {
      section: 'receive', name: 'onMessage', kind: 'method', shared: 'onMessage(handler: async (Message) -> void) -> Subscription',
      platforms: {
        swift: 'func onMessage(_ handler: @escaping (Message) async throws -> Void) throws -> Subscription',
        kotlin: 'fun onMessage(handler: suspend (Message) -> Unit): Subscription',
        typescript: 'onMessage(handler: (message: Message) => Promise<void>): () => void',
      },
      meaning: 'Registers the one message handler, and registering it starts receiving. The library awaits the handler and acks the message after it returns. A throw retries the message, up to the handler attempts below, then reports `handlerGaveUp`. Cancelling the `Subscription` pauses receiving.',
      action: 'Finish storing the message before the handler returns. Make the handler safe to run twice for one `MessageId`.',
      throws: ['messageHandlerAlreadySet'],
      facts: ['handlerAttempts'],
      source: { adr: [adr, 'trueseal-sync ADR-0026'], sketch: true },
      gap: 'today messages arrive on a stream or event, with no awaited handler',
    },
    {
      section: 'receive', name: 'Message', kind: 'type', shared: 'Message{id: MessageId, from: Member, body: bytes}',
      platforms: {
        swift: 'Message(id: MessageID, from: Member, body: Data)',
        kotlin: 'Message(id: MessageId, from: Member, body: ByteArray)',
        typescript: 'interface Message { id: MessageId; from: Member; body: Uint8Array }',
      },
      meaning: 'One received message. `from.id` is the same id as in `members`. `body` is the bytes the sender passed to `send()`.',
      source: { adr: [adr], sketch: true },
      gap: 'today TS uses `Buffer`, and no SDK carries a `Member` as the sender',
    },
    {
      section: 'receive', name: 'MessageId', kind: 'type', shared: 'MessageId',
      platforms: { swift: 'MessageID', kotlin: 'MessageId', typescript: 'MessageId' },
      meaning: 'An opaque message id, the same on sender and receiver. The library drops duplicates by it before the handler runs.',
      action: 'Store it as given. Never parse or rebuild it.',
      aliases: ['MessageID'],
      source: { adr: [adr, 'trueseal-sync ADR-0020'], sketch: true },
      todo: 'TODO: no ADR fixes the underlying type of `MessageId`.',
    },
    {
      section: 'send', name: 'send', kind: 'method', shared: 'async send(body: bytes) -> MessageId',
      platforms: {
        swift: 'func send(_ body: Data) async throws -> MessageID',
        kotlin: 'suspend fun send(body: ByteArray): MessageId',
        typescript: 'send(body: Uint8Array): Promise<MessageId>',
      },
      meaning: 'Queues `body` for every other member. It returns once the message is in the durable outbox, never after delivery. Bodies are opaque bytes.',
      action: 'Keep the returned `MessageId` to match a later `sendFailed`.',
      throws: ['payloadTooLarge', 'notMember'],
      facts: ['protocolSizeLimit'],
      source: { adr: [adr, 'trueseal-sync ADR-0025', 'trueseal-sync ADR-0026'], sketch: true },
      gap: 'today Swift and Kotlin call the method `publish`, with a text overload, TS `send` takes a `Buffer`, and none returns a `MessageId`',
    },
    {
      section: 'pairing', name: 'startPairing', kind: 'method', shared: 'startPairing() -> string',
      platforms: { swift: 'func startPairing() throws -> String', kotlin: 'fun startPairing(): String', typescript: 'startPairing(): string' },
      meaning: 'Opens the pairing window on an admitting device and returns the Pairing Token. Join requests arrive as `joinRequest` events.',
      action: 'Show the token as a QR code or copyable text on the admitting device.',
      source: { adr: [adr, 'trueseal-sync ADR-0023'], sketch: true },
      gap: 'today the method is `generatePairingToken` (Swift, Kotlin) or `pairingToken` (TS)',
      todo: 'TODO: no ADR names the error `startPairing` raises outside `member`.',
    },
    {
      section: 'pairing', name: 'accept', kind: 'method', shared: 'async accept(request: JoinRequest)',
      platforms: { swift: 'func accept(_ request: JoinRequest) async throws', kotlin: 'suspend fun accept(request: JoinRequest)', typescript: 'accept(request: JoinRequest): Promise<void>' },
      meaning: 'Admits the device that sent `request`. The window closes after it.',
      action: 'Call it only after the user confirms the request comes from the device in front of them.',
      throws: ['pairingClosed', 'groupFull'],
      facts: ['maxGroupSize'],
      source: { adr: [adr, 'trueseal-sync ADR-0023'], sketch: true },
      gap: 'today the method is `acceptPairingRequest`',
    },
    {
      section: 'pairing', name: 'cancelPairing', kind: 'method', shared: 'cancelPairing()',
      platforms: { swift: 'func cancelPairing()', kotlin: 'fun cancelPairing()', typescript: 'cancelPairing(): void' },
      meaning: 'Closes the pairing window. There is no reject call; a request that was never accepted disappears when the window closes.',
      source: { adr: [adr, 'trueseal-sync ADR-0023'], sketch: true },
    },
    {
      section: 'pairing', name: 'JoinRequest', kind: 'type', shared: 'JoinRequest{id, name}',
      platforms: { swift: 'JoinRequest(id:name:)', kotlin: 'JoinRequest(id, name)', typescript: 'interface JoinRequest { id; name }' },
      meaning: 'A device asking to join. `name` is a label the device chose, never authentication.',
      source: { adr: [adr, 'trueseal-sync ADR-0023'], sketch: true },
      gap: 'today Swift and Kotlin use `PairingRequest(token, deviceName)`, and TS passes `(requestToken, name)` to a `memberRequest` listener',
    },
    {
      section: 'pairing', name: 'join', kind: 'method', shared: 'async join(token: string)',
      platforms: { swift: 'func join(_ token: String) async throws', kotlin: 'suspend fun join(token: String)', typescript: 'join(token: string): Promise<void>' },
      meaning: 'Asks to join the Sync Group behind `token` and moves the device to `pendingJoin`, which survives restarts. Once admitted, the device reports `statusChanged(member, joined)`.',
      throws: ['alreadyInGroup', 'invalidPairingToken'],
      source: { adr: [adr, 'trueseal-sync ADR-0023'], sketch: true },
      gap: 'today the method is `joinGroup`',
    },
    {
      section: 'pairing', name: 'cancelJoin', kind: 'method', shared: 'cancelJoin()',
      platforms: { swift: 'func cancelJoin()', kotlin: 'fun cancelJoin()', typescript: 'cancelJoin(): void' },
      meaning: 'Moves a `pendingJoin` device back to `notJoined`.',
      source: { adr: [adr], sketch: true },
      gap: missingToday,
    },
    {
      section: 'membership', name: 'remove', kind: 'method', shared: 'async remove(memberId: Member.id)',
      platforms: { swift: 'func remove(_ memberId: Member.ID) async throws', kotlin: 'suspend fun remove(memberId: String)', typescript: 'remove(memberId: string): Promise<void>' },
      meaning: 'Removes another member. Any member may remove any other member. The removed device wipes and makes a fresh identity.',
      source: { adr: [adr, 'trueseal-sync ADR-0027'], sketch: true },
      gap: 'today the method is `removeMember`, taking a `SyncMember` in Swift and Kotlin',
      todo: 'TODO: no ADR fixes the Swift and Kotlin member id type, which error `remove` raises outside `member`, or whether it raises `memberNotFound`.',
    },
    {
      section: 'membership', name: 'leave', kind: 'method', shared: 'async leave()',
      platforms: { swift: 'func leave() async throws', kotlin: 'suspend fun leave()', typescript: 'leave(): Promise<void>' },
      meaning: 'Leaves the Sync Group. The device moves to `leaving`, then to `notJoined` with reason `left`.',
      source: { adr: [adr, 'trueseal-sync ADR-0027'], sketch: true },
      gap: missingToday,
      todo: 'TODO: no ADR names the error `leave` raises outside `member`.',
    },
    {
      section: 'membership', name: 'destroyGroup', kind: 'method', shared: 'async destroyGroup()',
      platforms: { swift: 'func destroyGroup() async throws', kotlin: 'suspend fun destroyGroup()', typescript: 'destroyGroup(): Promise<void>' },
      meaning: 'Ends the Sync Group for every member. The device stays `destroying` until the relay has accepted a Revoke for every member, with no timeout, then moves to `notJoined` with reason `destroyed`. Each member forwards the Revoke and wipes. An offline member wipes when it reconnects within the Relay TTL ceiling.',
      action: 'Show `destroying` until `statusChanged` reports `notJoined`, then pair again.',
      facts: ['relayTtlMax'],
      source: { adr: [adr, 'trueseal-sync ADR-0029'], sketch: true },
      gap: 'today Revoke is sent once without retry, and the session is unusable afterwards',
      todo: 'TODO: trueseal-sync ADR-0029 says `destroyGroup()` in `pendingJoin` fails with "typed error: not in a group" without naming the case; the same holds for `notJoined`.',
    },
    {
      section: 'subscribe', name: 'onEvent', kind: 'method', shared: 'onEvent(listener: (event) -> void) -> Subscription',
      platforms: {
        swift: 'trueseal.onEvent { event in … } -> Subscription',
        kotlin: 'fun onEvent(listener: (TrueSealEvent) -> Unit): Subscription',
        typescript: 'onEvent(listener: (event) => void): () => void',
      },
      meaning: 'Registers an event listener. Any number may be registered. Events raised before the first listener are buffered.',
      aliases: ['TrueSealEvent'],
      source: { adr: [adr], sketch: true },
      gap: subscribeGap,
      todo: typeNameTodo,
    },
    {
      section: 'subscribe', name: 'onDeliveryIssue', kind: 'method', shared: 'onDeliveryIssue(listener: (issue) -> void) -> Subscription',
      platforms: {
        swift: 'trueseal.onDeliveryIssue { issue in … } -> Subscription',
        kotlin: 'fun onDeliveryIssue(listener: (DeliveryIssue) -> Unit): Subscription',
        typescript: 'onDeliveryIssue(listener: (issue) => void): () => void',
      },
      meaning: 'Registers a delivery-issue listener. It is optional, and ignoring issues is safe. Every issue stays on the device; nothing goes back to the sender.',
      aliases: ['DeliveryIssue'],
      source: { adr: [adr, 'trueseal-sync ADR-0026'], sketch: true },
      gap: subscribeGap,
      todo: typeNameTodo,
    },
    {
      section: 'subscribe', name: 'Subscription', kind: 'type', shared: 'Subscription.cancel()',
      platforms: { swift: 'Subscription.cancel()', kotlin: 'Subscription.cancel()', typescript: '() => void (call it to unsubscribe)' },
      meaning: 'The handle every `on` call returns. Cancelling it removes the handler or listener.',
      fields: ['cancel'],
      source: { adr: [adr], sketch: true },
      gap: missingToday,
    },
    {
      section: 'info', name: 'TrueSeal.info', kind: 'constant', shared: 'TrueSeal.info: {sdkVersion, transportVersion, endToEndVersion}',
      platforms: {
        swift: 'TrueSeal.info: {sdkVersion, transportVersion, endToEndVersion}',
        kotlin: 'TrueSeal.info: {sdkVersion, transportVersion, endToEndVersion}',
        typescript: 'TrueSeal.info: {sdkVersion, transportVersion, endToEndVersion}',
      },
      meaning: 'The TrueSeal Release of this SDK and the Protocol Versions it speaks. Nothing is negotiated.',
      fields: ['sdkVersion', 'transportVersion', 'endToEndVersion'],
      facts: ['trueSealRelease', 'transportVersion', 'endToEndVersion'],
      source: { adr: [adr, 'trueseal-sync ADR-0022', 'trueseal-sync ADR-0030'] },
      gap: missingToday,
    },
    {
      section: 'info', name: 'TrueSeal.maxPayloadBytes', kind: 'constant', shared: 'TrueSeal.maxPayloadBytes',
      platforms: { swift: 'TrueSeal.maxPayloadBytes', kotlin: 'TrueSeal.MAX_PAYLOAD_BYTES', typescript: 'TrueSeal.MAX_PAYLOAD_BYTES' },
      meaning: 'The largest body `send()` accepts, in bytes.',
      aliases: ['MAX_PAYLOAD_BYTES'],
      facts: ['protocolSizeLimit'],
      source: { adr: [adr, 'trueseal-sync ADR-0025'], sketch: true },
      gap: missingToday,
    },
    {
      section: 'info', name: 'TrueSeal.maxGroupSize', kind: 'constant', shared: 'TrueSeal.maxGroupSize',
      platforms: { swift: 'TrueSeal.maxGroupSize', kotlin: 'TrueSeal.MAX_GROUP_SIZE', typescript: 'TrueSeal.MAX_GROUP_SIZE' },
      meaning: 'The most devices one Sync Group holds.',
      aliases: ['MAX_GROUP_SIZE'],
      facts: ['maxGroupSize'],
      source: { adr: [adr, 'trueseal-sync ADR-0027'], sketch: true },
      gap: missingToday,
    },
    {
      section: 'errors', name: 'TrueSealError', kind: 'type', shared: 'TrueSealError',
      platforms: {
        swift: 'enum TrueSealError: Error',
        kotlin: 'sealed class TrueSealException : Exception',
        typescript: 'class TrueSealError extends Error { code; max?; status? }',
      },
      meaning: 'The error a failing call throws. Its case is one of the cases below, and the case fields are typed extras.',
      aliases: ['TrueSealException'],
      source: { adr: [adr, 'trueseal-sync ADR-0032'], sketch: true },
      gap: 'today each SDK has `TruesealSyncError` with 8 cases (`invalidRelayURL`, `pushFailed`, `notInGroup`, `groupDestroyed` and others), TS has no `code`, and `ffi.rs` reports store errors as `InvalidNamespace`',
    },
  ],
} satisfies ApiReference;
